trigger:
  - main
  - develop

resources:
  repositories:
    - repository: templates
      type: git
      name: util_pipeline

extends:
  template: pipeline-base/ts.yml@templates
  parameters:
    par_typeTask: StaticEC2
    par_repoName: <<repository-name>>
    par_sizeStaticEC2: sm